# -----------------------------
# Logging
# -----------------------------
/RMG/Manager/Logging/LogLevel detail  # options: debug, info, warning, error
/RMG/Processes/OpticalPhysics True
/RMG/Processes/OpticalPhysicsMaxOneWLSPhoton True
/tracking/verbose 0


# -----------------------------
# Register Detectors
# -----------------------------

/RMG/Geometry/RegisterDetector Germanium   BEGe_pv  101
/RMG/Geometry/RegisterDetector Germanium   ICPC_pv  102

/RMG/Geometry/RegisterDetector Scintillator enclosure_bege_pv 201
/RMG/Geometry/RegisterDetector Scintillator enclosure_icpc_pv 202

/RMG/Geometry/RegisterDetector Scintillator LAr_pv 401

# Optical channels (SiPMs)
# top ring
/RMG/Geometry/RegisterDetector Optical sipm_top_0 1000
/RMG/Geometry/RegisterDetector Optical sipm_top_1 1002
/RMG/Geometry/RegisterDetector Optical sipm_top_2 1004
/RMG/Geometry/RegisterDetector Optical sipm_top_3 1006
/RMG/Geometry/RegisterDetector Optical sipm_top_4 1008
/RMG/Geometry/RegisterDetector Optical sipm_top_5 1010

# bottom ring
/RMG/Geometry/RegisterDetector Optical sipm_bot_0 1001
/RMG/Geometry/RegisterDetector Optical sipm_bot_1 1003
/RMG/Geometry/RegisterDetector Optical sipm_bot_2 1005
/RMG/Geometry/RegisterDetector Optical sipm_bot_3 1007
/RMG/Geometry/RegisterDetector Optical sipm_bot_4 1009
/RMG/Geometry/RegisterDetector Optical sipm_bot_5 1011


# Optional: register LAr if you want it as an active volume


# -----------------------------
# Initialize Run
# -----------------------------
/run/initialize

# -----------------------------
# Source / Generator
# -----------------------------
/RMG/Generator/Confine Volume
/RMG/Generator/Confinement/Physical/AddVolume LAr_pv


/RMG/Generator/Select GPS

/gps/particle ion
/gps/energy 0 eV
/gps/ion 83 207


# -----------------------------
# Start Simulation
# -----------------------------
/run/beamOn 6000000
