######################################################
# Logging
######################################################
/RMG/Manager/Logging/LogLevel detail

######################################################
# Geometry setup
######################################################

/RMG/Geometry/RegisterDetector Germanium   BEGe_pv     101
/RMG/Geometry/RegisterDetector Germanium   ICPC_pv     102

/RMG/Geometry/RegisterDetector Scintillator enclosure_bege_pv 201
/RMG/Geometry/RegisterDetector Scintillator enclosure_icpc_pv 202

/RMG/Geometry/RegisterDetector Scintillator LAr_pv 401

# Optical channels (SiPMs)
# top ring
/RMG/Geometry/RegisterDetector Optical sipm_top_0 1000
/RMG/Geometry/RegisterDetector Optical sipm_top_1 1002
/RMG/Geometry/RegisterDetector Optical sipm_top_2 1004
/RMG/Geometry/RegisterDetector Optical sipm_top_3 1006
/RMG/Geometry/RegisterDetector Optical sipm_top_4 1008
/RMG/Geometry/RegisterDetector Optical sipm_top_5 1010

# bottom ring
/RMG/Geometry/RegisterDetector Optical sipm_bot_0 1001
/RMG/Geometry/RegisterDetector Optical sipm_bot_1 1003
/RMG/Geometry/RegisterDetector Optical sipm_bot_2 1005
/RMG/Geometry/RegisterDetector Optical sipm_bot_3 1007
/RMG/Geometry/RegisterDetector Optical sipm_bot_4 1009
/RMG/Geometry/RegisterDetector Optical sipm_bot_5 1011

/run/initialize

######################################################
# Visualization setup (RMG safe)
######################################################
/vis/open OGL

# Geometry style
/vis/viewer/set/style wireframe
/vis/viewer/set/auxiliaryEdge true
/vis/viewer/set/lineSegmentsPerCircle 100

# Draw the volume
/vis/drawVolume

# Background and default color
/vis/viewer/set/background white
/vis/viewer/set/defaultColour 0.5 0.5 0.5  # grey for everything

# Add coordinate axes
/vis/scene/add/axes 0 0 0 100 mm

# Camera viewpoint and zoom
/vis/viewer/set/viewpointThetaPhi 90 0
/vis/viewer/zoom 1.2

######################################################
# Event visualization
######################################################
/vis/scene/add/trajectories smooth
/vis/scene/add/hits
/vis/scene/endOfEventAction accumulate

/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2

######################################################
# Source setup
######################################################
/RMG/Generator/Confine Volume
/RMG/Generator/Confinement/Physical/AddVolume LAr_pv

/RMG/Generator/Select GPS
/gps/particle gamma
/gps/ang/type iso
/gps/energy 1000 keV

######################################################
# Run
######################################################
/run/beamOn 10000
